### ISSUE TITLE
请问能否在android或者Ios上面，导出成视频格式。

### ISSUE THREAD

**Issue by GodXJ** [libpag/libpag#1]
#### 问题

> 告诉我们你遇到了什么问题。

#### 重现

> 说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 issue 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：iPhone 7（iOS 12），OnePlus 7（Android 10），iMac 5K（macOS 10.15.3）

#### Demo（可选）

> 给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 添加其他内容

**Comment by domchen** [comment]
导出视频不是PAG动画方案做的，PAG只负责渲染动画。在iOS上可以把PAG渲染到到一个CVPIxelBuffer上，然后使用AVFoundation的代码导出成视频即可。
