### ISSUE TITLE
PAGMovie 调用FromVideoPath 和FromVideoPath startTime:方法返回空

### ISSUE THREAD

**Issue by 794815443** [libpag/libpag#11]
PAGMovie 调用FromVideoPath 和FromVideoPath startTime:方法返回空，传入的demo中的mp4和本地视频都返回nil

**Comment by lvpengwei** [comment]
对外发布的版本是没有实现接口的

**Comment by 794815443** [comment]
请问短期之内会发布实现这个类的版本吗？或者说现在实现的版本有没有替代方案

**Comment by lvpengwei** [comment]
可以借用其他的视频播放框架，在解出每一帧数据进行处理的时候，用 PAGImage 包装帧数据替换到 PAG 里面渲染。

**Comment by 794815443** [comment]
我看到demo中VideoViewController这个类有类似的实现，不过有内存问题，我换一个框架试一下，应该不麻烦。我的场景是预览图片和视频，支持更换效果

**Comment by lvpengwei** [comment]
好的

**Comment by 794815443** [comment]
大佬，请问一下近期sdk有没有开放pagmovie实现的计划，我这边要做音乐相册，类似腾讯相册管家，视频和图片混合那种。我昨天使用了demo解码视频的方法，也解决了内存问题，但是和图片混合的话，没法控制时间以及进度

**Comment by 794815443** [comment]
大佬，请问一下近期sdk有没有开放pagmovie实现的计划，我这边要做音乐相册，类似腾讯相册管家，视频和图片混合那种。我昨天使用了demo解码视频的方法，也解决了内存问题，但是和图片混合的话，没法控制时间以及进度
