### ISSUE TITLE
No implementation found for void org.libpag.PAGPlayer.nativeInit()

### ISSUE THREAD

**Issue by 925999193** [libpag/libpag#12]
我是在flutter中接入sdk，但是在安卓实现加载pag文件并播放时出现该问题

**Comment by domchen** [comment]
这个意思是你的c++库的so没有加载到。如果是使用标准的AAR内置接入是不用加载的，可以检查一下是否用了动态加载，动态加载是否成功。另外还有架构的问题，比如你们同时需要32位和64位的，但是只提供了32位的so加载，也会出现找不到接口。

**Comment by domchen** [comment]
可以检查一下，如果还有问题可以加QQ群893379574，我们协助排查。
