### ISSUE TITLE
使用多个PAGView有概率死锁

### ISSUE THREAD

**Issue by EZElkins** [libpag/libpag#13]
libpag 版本：libpag-ios（v3.2.4.37）

主线程backtrace如下
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00000001b83fec10 libsystem_kernel.dylib`__psynch_mutexwait + 8
    frame #1: 0x00000001b8322808 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_wait + 92
    frame #2: 0x00000001b8322778 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_slow + 260
    frame #3: 0x00000001b848510c libc++.1.dylib`std::__1::mutex::lock() + 16
    frame #4: 0x000000010de6410c libpag`___lldb_unnamed_symbol182$$libpag + 40
    frame #5: 0x000000010dec14dc libpag`pag::PAGPlayer::setProgress(double) + 80
    frame #6: 0x000000010decfd88 libpag`-[PAGView onAnimationUpdate:] + 40
    frame #7: 0x000000010df037f8 libpag`___lldb_unnamed_symbol1730$$libpag + 192
    frame #8: 0x000000010df033ac libpag`___lldb_unnamed_symbol1725$$libpag + 192
    frame #9: 0x0000000111998114 GPUToolsCore`-[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 172
    frame #10: 0x00000001bf13b354 QuartzCore`CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 512
    frame #11: 0x00000001bf20b1a4 QuartzCore`display_timer_callback(__CFMachPort*, void*, long, void*) + 268
    frame #12: 0x00000001b8569584 CoreFoundation`__CFMachPortPerform + 176
    frame #13: 0x00000001b8593f44 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
    frame #14: 0x00000001b85935e8 CoreFoundation`__CFRunLoopDoSource1 + 452
    frame #15: 0x00000001b858e0e0 CoreFoundation`__CFRunLoopRun + 1880
    frame #16: 0x00000001b858d660 CoreFoundation`CFRunLoopRunSpecific + 480
    frame #17: 0x00000001c299e604 GraphicsServices`GSEventRunModal + 164
    frame #18: 0x00000001bc76215c UIKitCore`UIApplicationMain + 1944

**Comment by lvpengwei** [comment]
你可以尝试升到最新，目前最新版是 3.2.7.25

**Comment by EZElkins** [comment]
> 你可以尝试升到最新，目前最新版是 3.2.7.25

好的  我升级完观察观察
