### ISSUE TITLE
pag支持ae表达式吗

### ISSUE THREAD

**Issue by kimown** [libpag/libpag#14]

**Comment by domchen** [comment]
你好，目前PAG还不支持直接导出表达式，但是可以用两种方式实现带表达式效果的导出：1.在图层上右键可以把表达式转换为关键帧，然后就可以导出了。2.把含有表达式的图层放进一个名字带  _bmp 后缀的预合成里即可按截图方式导出。同样也适用于所有目前还不能直接导出的AE特效，包括第三方的AE插件。具体可以参考：https://pag.io/docs/pag-export.html 。还有问题也可以加入 QQ群提问： 893379574
