### ISSUE TITLE
bug-最新版本（0730）sdk在Android 5.1.1 rk3288主板无法渲然动画页面

### ISSUE THREAD

**Issue by alitong** [libpag/libpag#15]
#### 问题

> 告诉我们你遇到了什么问题。

#### 重现

> 说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 issue 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：iPhone 7（iOS 12），OnePlus 7（Android 10），iMac 5K（macOS 10.15.3）

#### Demo（可选）

> 给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 添加其他内容

**Comment by domchen** [comment]
请提供一个可复现的Demo，否则我们没法帮到你定位问题。可以先尝试一下在官方的demo工程里复现一下，另外看一下是否其他设备上也能出现。需要进一步的协助可以加一下QQ群：893379574 。
