### ISSUE TITLE
10月14日，上传appstore会报错 libpag.framework' contains an invalid value '[iPhoneSimulator]'

### ISSUE THREAD

**Issue by make1a** [libpag/libpag#16]
### 问题描述

pod 'libpag', '~>3.2.4.37' 

COCOAPODS: 1.11.2

10月13日上传App Store 正常。
10月14日 22:40分上传App Store会报错

ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/Frameworks/libpag.framework' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
![100751634223522_ pic_hd](https://user-images.githubusercontent.com/17469549/137343830-b8ee9dd5-4582-4d49-b84f-4cf3c469b165.jpg)

**Comment by make1a** [comment]
用的这个版本上架过很多次了。最近的一次13号还能上传，昨天晚上突然就不行了。可能是苹果更新了上传App Store的校验吧

**Comment by ZexiFangkong** [comment]
大佬们, 可以更新个新版本吗, 今天要发个版本咯
