### ISSUE TITLE
replaceText方法替换setTextData方法

### ISSUE THREAD

**Issue by swiftieslizheng** [libpag/libpag#2]
#### 问题

> 运行下载的demo，把pagView.setTextData替换成pagFile.replaceText发现无效。

#### 重现

> 

#### 环境

libpag 版本:，libpag-android（v3.2.5.1） 
设备： pixel 2 api28

**Comment by domchen** [comment]
你好，请提供一下你出问题的demo。在issue里上传或者加一下QQ交流群893379574咨询都可以。 @swiftieslizheng
