### ISSUE TITLE
动画一闪一闪

### ISSUE THREAD

**Issue by zhangchaojiong** [libpag/libpag#3]
### 问题描述
动画一闪一闪，android 端有问题，ios 无问题

**Comment by zhangchaojiong** [comment]
[putoo_ugc_song_list.txt](https://github.com/libpag/libpag/files/5508244/putoo_ugc_song_list.txt)
请把 txt 改成 pag ,然后在android 端接入，就能复现此问题

**Comment by lvpengwei** [comment]
@zhangchaojiong 麻烦问下手机型号，系统版本。
我用测试项目[pag-android](https://github.com/libpag/pag-android)，测试机 一加7(Android 10) 没重现

**Comment by zhangchaojiong** [comment]
> @zhangchaojiong 麻烦问下手机型号，系统版本。
> 我用测试项目[pag-android](https://github.com/libpag/pag-android)，测试机 一加7(Android 10) 没重现

我用的 小米 8

**Comment by zhangchaojiong** [comment]
我录制了一个视屏 ，你看一下。
[device-2020-11-09-205417.mp4.zip](https://github.com/libpag/libpag/files/5510643/device-2020-11-09-205417.mp4.zip)

**Comment by lvpengwei** [comment]
企业微信已沟通

**Comment by songxiaoliang** [comment]
啥也不说，怎么解决的啊

**Comment by lvpengwei** [comment]
> 啥也不说，怎么解决的啊

这个问题，通过升级 PAG 版本解决了，之前用的是比较旧的
