### ISSUE TITLE
请问下 ios有没有可以监听动画播放实时进度的API

### ISSUE THREAD

**Issue by ShiHaoXie** [libpag/libpag#5]
#### 问题

> 告诉我们你遇到了什么问题。

#### 重现

> 说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 issue 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：iPhone 7（iOS 12），OnePlus 7（Android 10），iMac 5K（macOS 10.15.3）

#### Demo（可选）

> 给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 添加其他内容

**Comment by domchen** [comment]
有，onAnimationStart， onAnimationEnd，onAnimationCancel和onAnimationRepeat。请参考这里：https://pag.io/api.html#/apis/ios/Protocols/PAGViewListener.html。如果你的目的是只播放一个区间，不需要监听实时进度每帧来判断一下这么麻烦。有更简单的API，一次调用就行。PAGFile是可以任意组合修改包括调整时长的。你只需调用PAGFile.setStartTime和startDuration就可以控制播放的区间了。你也可以多个PAGFile组合到一起播放。创建一个空的PAGComposition，addLayer() 多个PAGFile到它里面，可以分别对每个PAGFile设置startTIme和duration以及matrix控制位置。然后把总的PAGComposition设置给PAGView播放即可。
