### ISSUE TITLE
请问PAGView 获取到的SurfaceTexture使用MediaCodec如何编码成mp4，可以给段编码mp4的事例代码吗？

### ISSUE THREAD

**Issue by it212** [libpag/libpag#6]

**Comment by kevingpqi123** [comment]
最近提这个问题的开发同学蛮多，我们完善下demo工程，预计下周给大家一个范例

**Comment by lvpengwei** [comment]
https://github.com/libpag/pag-android/blob/master/sample/app/src/main/java/com/tencent/libpag/sample/libpag_sample/APIsDetailActivity.java

@it212
