### ISSUE TITLE
非常好用，希望可以尽快支持web端的使用

### ISSUE THREAD

**Issue by shuxialanhu** [libpag/libpag#7]
#### 问题

> 告诉我们你遇到了什么问题。

#### 重现

> 说明重现步骤。加载的是什么文件，你的代码是怎么写的，等等。
> PAG 素材可以在压缩之后，随这个 issue 上传。

#### 环境

libpag 版本：libpag-ios（v3.2.4.37），libpag-android（v3.2.5.1），PAGViewer（2.1.33 beta）  
设备：iPhone 7（iOS 12），OnePlus 7（Android 10），iMac 5K（macOS 10.15.3）

#### Demo（可选）

> 给一个 Demo 项目，我们可以运行并重现这个问题。

#### 其他（可选）

> 添加其他内容

**Comment by domchen** [comment]
Web版本大概在2021年中会支持，要排在PAG 4.0版本发布之后。

**Comment by Zhaiaiguo518** [comment]
> Web版本大概在2021年中会支持，要排在PAG 4.0版本以后发布。

你好，请问web版本在浏览器可以自动播放，但是在app和微信中报没有权限是因为什么原因？

**Comment by zenoslin** [comment]
> > Web版本大概在2021年中会支持，要排在PAG 4.0版本以后发布。
> 
> 你好，请问web版本在浏览器可以自动播放，但是在app和微信中报没有权限是因为什么原因？

@Zhaiaiguo518 因为PAG Web版的视频序列帧使用了浏览器的Video标签的解码能力。
在微信App的浏览器中，在用户产生交互之前是不允许播放视频的，所以这个时候会跑错没有play权限。
这个规则不属于标准的Web规则，我们的SDK是根据Web标准编写的，所以会出现这种差异的情况。
针对特定的浏览器规则，我们建议是在业务侧去进行规避优化，例如先用静态图片占位，等用户交互后再使用PAG。
